### ISSUE TITLE
0.5.1 fails to build on windows

### ISSUE THREAD

**Issue by RalfNorthman** [Trivernis/embed-nu#1]
Hi! Cool project!

## The problem

I got an error building embed-nu as a dependency, so I cloned the repo: same thing there:

```
error[E0425]: cannot find value `Exec` in this scope
   --> src\context\bindings.rs:155:9
    |
155 |         Exec,
    |         ^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `embed-nu` due to previous error
```

## Head scratching

There's a `use nu_command::*;` in the offending file and in the docs for nu_command 0.75.0 there seems to be an `Exec` struct visible in the crate root so it _should_ be in scope, so at this point I don't know what's going on. With line 155 commented out it builds fine and passes the tests.

I'm on windows 10 and tried with both rust stable 1.65 and 1.67.1.

## Possible solution

I also tried to compile on a VM with ubuntu 22.04 and rust stable 1.66.1, **there it works no problem!**

So I think `Exec` is hidden behind a `#[cfg(unix)]` somewhere in the nushell source code since the nu docs says **exec** is unix only:
https://www.nushell.sh/commands/docs/exec.html

So with two variants of `bind_system_commands` I think the problem would be solved. Maybe something like this:

```rust
#[cfg(unix)]
pub fn bind_system_commands(engine_state: &mut EngineState) -> CrateResult<()> {
    bind_commands! {
        engine_state,
        Benchmark,
        Complete,
        Exec,
        External,
        NuCheck,
        Sys,
        Ps,
        Which,
    }
}

#[cfg(not(unix))]
pub fn bind_system_commands(engine_state: &mut EngineState) -> CrateResult<()> {
    bind_commands! {
        engine_state,
        Benchmark,
        Complete,
        External,
        NuCheck,
        Sys,
        Ps,
        Which,
    }
}
```

I could make a PR with this if you like.

**Comment by Trivernis** [comment]
You're right. I had a look at `nu_command`. Exec is only available on unix. I think it would make more sense to either get rid of platform specific commands in `embed_nu` or move them to a platform specific module that needs to be enabled explicitly.

**Comment by RalfNorthman** [comment]
I don't think I need `exec` for the use-case I had in mind, but with that said I think the crate should have support for it eventually.

**Comment by Trivernis** [comment]
I applied a hotfix to put those commands behind a compiler flag for now. I'm not entirely satisfied with this yet though

**Comment by RalfNorthman** [comment]
Great!

One thing: I notice you have the two variants of `bind_system_commands` as `#[cfg(unix)]` and `#[cfg(windows)]` (instead of `#[cfg(unix)]` and `#[cfg(not(unix))]` as I proposed above). I'm no expert in this, but isn't there rust-supported platforms that are neither unix nor windows? If this is the case those platforms will now fail to build `embed_nu`.

**Comment by Trivernis** [comment]
Oh, I see, there might be cases where neither is true. The windows-specific bindings add the `RegistryQuery` command so I have to add a third option for systems that are neither windows now unix.
